"""Type stubs for thorvg_cython.thorvg — Cython bindings for ThorVG."""

from __future__ import annotations

from enum import IntEnum
from typing import Sequence, overload

# ═══════════════════════════════════════════════════════════════════
#  Enumerations
# ═══════════════════════════════════════════════════════════════════

class Result(IntEnum):
    SUCCESS: int
    INVALID_ARGUMENT: int
    INSUFFICIENT_CONDITION: int
    FAILED_ALLOCATION: int
    MEMORY_CORRUPTION: int
    NOT_SUPPORTED: int
    UNKNOWN: int

class Colorspace(IntEnum):
    ABGR8888: int
    ARGB8888: int
    ABGR8888S: int
    ARGB8888S: int
    UNKNOWN: int

class EngineOption(IntEnum):
    NONE: int
    DEFAULT: int
    SMART_RENDER: int

class MaskMethod(IntEnum):
    NONE: int
    ALPHA: int
    INVERSE_ALPHA: int
    LUMA: int
    INVERSE_LUMA: int
    ADD: int
    SUBTRACT: int
    INTERSECT: int
    DIFFERENCE: int
    LIGHTEN: int
    DARKEN: int

class BlendMethod(IntEnum):
    NORMAL: int
    MULTIPLY: int
    SCREEN: int
    OVERLAY: int
    DARKEN: int
    LIGHTEN: int
    COLORDODGE: int
    COLORBURN: int
    HARDLIGHT: int
    SOFTLIGHT: int
    DIFFERENCE: int
    EXCLUSION: int
    HUE: int
    SATURATION: int
    COLOR: int
    LUMINOSITY: int
    ADD: int
    COMPOSITION: int

class TvgType(IntEnum):
    UNDEF: int
    SHAPE: int
    SCENE: int
    PICTURE: int
    TEXT: int
    LINEAR_GRAD: int
    RADIAL_GRAD: int

class PathCommand(IntEnum):
    CLOSE: int
    MOVE_TO: int
    LINE_TO: int
    CUBIC_TO: int

class StrokeCap(IntEnum):
    BUTT: int
    ROUND: int
    SQUARE: int

class StrokeJoin(IntEnum):
    MITER: int
    ROUND: int
    BEVEL: int

class StrokeFill(IntEnum):
    PAD: int
    REFLECT: int
    REPEAT: int

class FillRule(IntEnum):
    NON_ZERO: int
    EVEN_ODD: int

class TextWrap(IntEnum):
    NONE: int
    CHARACTER: int
    WORD: int
    SMART: int
    ELLIPSIS: int
    HYPHENATION: int

class FilterMethod(IntEnum):
    BILINEAR: int
    NEAREST: int

# ═══════════════════════════════════════════════════════════════════
#  Data classes
# ═══════════════════════════════════════════════════════════════════

class ColorStop:
    __slots__: tuple[str, ...]
    offset: float
    r: int
    g: int
    b: int
    a: int
    def __init__(self, offset: float, r: int, g: int, b: int, a: int = 255) -> None: ...

class Point:
    __slots__: tuple[str, ...]
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...

class Matrix:
    __slots__: tuple[str, ...]
    e11: float
    e12: float
    e13: float
    e21: float
    e22: float
    e23: float
    e31: float
    e32: float
    e33: float
    def __init__(
        self,
        e11: float = 1, e12: float = 0, e13: float = 0,
        e21: float = 0, e22: float = 1, e23: float = 0,
        e31: float = 0, e32: float = 0, e33: float = 1,
    ) -> None: ...

class TextMetrics:
    __slots__: tuple[str, ...]
    ascent: float
    descent: float
    linegap: float
    advance: float
    def __init__(
        self,
        ascent: float = 0, descent: float = 0,
        linegap: float = 0, advance: float = 0,
    ) -> None: ...

# ═══════════════════════════════════════════════════════════════════
#  PixelBuffer
# ═══════════════════════════════════════════════════════════════════

class PixelBuffer:
    """Heap-allocated RGBA pixel buffer implementing PEP 3118 buffer protocol."""
    def __init__(self, w: int, h: int, cs: int = 0, stride: int = 0) -> None: ...
    def __getbuffer__(self, buffer: object, flags: int) -> None: ...
    def __releasebuffer__(self, buffer: object) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride(self) -> int: ...
    @property
    def colorspace(self) -> Colorspace: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    def clear(self) -> None: ...

# ═══════════════════════════════════════════════════════════════════
#  Engine
# ═══════════════════════════════════════════════════════════════════

class Engine:
    threads: int
    def __init__(self, threads: int = 0) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
    @property
    def init_result(self) -> Result: ...
    def init(self, threads: int = 0) -> Result: ...
    def term(self) -> Result: ...
    def version(self) -> tuple[Result, int, int, int, str | None]: ...

# ═══════════════════════════════════════════════════════════════════
#  Paint
# ═══════════════════════════════════════════════════════════════════

class Paint:
    def __init__(self) -> None: ...
    def ref(self) -> int: ...
    def deref(self, free: bool = False) -> int: ...
    def get_ref(self) -> int: ...
    def capsule(self) -> object: ...
    def set_visible(self, visible: bool) -> Result: ...
    def get_visible(self) -> bool: ...
    def scale(self, factor: float) -> Result: ...
    def rotate(self, degree: float) -> Result: ...
    def translate(self, x: float, y: float) -> Result: ...
    def set_transform(self, m: Matrix) -> Result: ...
    def get_transform(self) -> tuple[Result, Matrix]: ...
    def set_opacity(self, opacity: int) -> Result: ...
    def get_opacity(self) -> tuple[Result, int]: ...
    def duplicate(self) -> Paint | None: ...
    def intersects(self, x: int, y: int, w: int, h: int) -> bool: ...
    def get_aabb(self) -> tuple[Result, float, float, float, float]: ...
    def get_obb(self) -> tuple[Result, list[Point]]: ...
    def set_mask_method(self, target: Paint, method: int) -> Result: ...
    def get_mask_method(self, target: Paint) -> tuple[Result, MaskMethod]: ...
    def set_clip(self, clipper: Paint) -> Result: ...
    def get_clip(self) -> Paint | None: ...
    def get_parent(self) -> Paint | None: ...
    def get_type(self) -> tuple[Result, TvgType]: ...
    def set_blend_method(self, method: int) -> Result: ...
    def _rel(self) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Canvas
# ═══════════════════════════════════════════════════════════════════

class Canvas:
    def __init__(self) -> None: ...
    def destroy(self) -> Result: ...
    def add(self, paint: Paint) -> Result: ...
    def insert(self, target: Paint, at: Paint | None = None) -> Result: ...
    def remove(self, paint: Paint | None = None) -> Result: ...
    def update(self) -> Result: ...
    def draw(self, clear: bool = True) -> Result: ...
    def sync(self) -> Result: ...
    def set_viewport(self, x: int, y: int, w: int, h: int) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Gradient
# ═══════════════════════════════════════════════════════════════════

class Gradient:
    def __init__(self) -> None: ...
    def set_color_stops(self, stops: Sequence[ColorStop]) -> Result: ...
    def get_color_stops(self) -> tuple[Result, list[ColorStop]]: ...
    def set_spread(self, spread: int) -> Result: ...
    def get_spread(self) -> tuple[Result, StrokeFill]: ...
    def set_transform(self, m: Matrix) -> Result: ...
    def get_transform(self) -> tuple[Result, Matrix]: ...
    def get_type(self) -> tuple[Result, TvgType]: ...
    def duplicate(self) -> Gradient | None: ...
    def _del(self) -> Result: ...

class LinearGradient(Gradient):
    def __init__(
        self, x1: float = 0, y1: float = 0, x2: float = 0, y2: float = 0,
    ) -> None: ...
    def set(self, x1: float, y1: float, x2: float, y2: float) -> Result: ...
    def get(self) -> tuple[Result, float, float, float, float]: ...

class RadialGradient(Gradient):
    def __init__(
        self,
        cx: float = 0, cy: float = 0, radius: float = 0,
        fx: float = 0, fy: float = 0, fr: float = 0,
    ) -> None: ...
    def set(
        self, cx: float, cy: float, r: float,
        fx: float = 0, fy: float = 0, fr: float = 0,
    ) -> Result: ...
    def get(self) -> tuple[Result, float, float, float, float, float, float]: ...

# ═══════════════════════════════════════════════════════════════════
#  Shape
# ═══════════════════════════════════════════════════════════════════

class Shape(Paint):
    def __init__(self) -> None: ...
    # path
    def reset(self) -> Result: ...
    def move_to(self, x: float, y: float) -> Result: ...
    def line_to(self, x: float, y: float) -> Result: ...
    def cubic_to(
        self, cx1: float, cy1: float, cx2: float, cy2: float,
        x: float, y: float,
    ) -> Result: ...
    def close(self) -> Result: ...
    def append_rect(
        self, x: float, y: float, w: float, h: float,
        rx: float = 0, ry: float = 0, cw: bool = True,
    ) -> Result: ...
    def append_circle(
        self, cx: float, cy: float, rx: float, ry: float, cw: bool = True,
    ) -> Result: ...
    def append_path(
        self, commands: Sequence[int | PathCommand],
        points: Sequence[Point | tuple[float, float]],
    ) -> Result: ...
    def get_path(self) -> tuple[Result, list[PathCommand], list[Point]]: ...
    # stroke
    def set_stroke_width(self, width: float) -> Result: ...
    def get_stroke_width(self) -> tuple[Result, float]: ...
    def set_stroke_color(
        self, r: int, g: int, b: int, a: int = 255,
    ) -> Result: ...
    def get_stroke_color(self) -> tuple[Result, int, int, int, int]: ...
    def set_stroke_gradient(self, grad: Gradient) -> Result: ...
    def get_stroke_gradient(self) -> tuple[Result, Gradient | None]: ...
    def set_stroke_dash(
        self, pattern: Sequence[float], offset: float = 0,
    ) -> Result: ...
    def get_stroke_dash(self) -> tuple[Result, list[float], float]: ...
    def set_stroke_cap(self, cap: int) -> Result: ...
    def get_stroke_cap(self) -> tuple[Result, StrokeCap]: ...
    def set_stroke_join(self, join: int) -> Result: ...
    def get_stroke_join(self) -> tuple[Result, StrokeJoin]: ...
    def set_stroke_miterlimit(self, ml: float) -> Result: ...
    def get_stroke_miterlimit(self) -> tuple[Result, float]: ...
    def set_trimpath(
        self, begin: float, end: float, simultaneous: bool = False,
    ) -> Result: ...
    # fill
    def set_fill_color(
        self, r: int, g: int, b: int, a: int = 255,
    ) -> Result: ...
    def get_fill_color(self) -> tuple[Result, int, int, int, int]: ...
    def set_fill_rule(self, rule: int) -> Result: ...
    def get_fill_rule(self) -> tuple[Result, FillRule]: ...
    def set_paint_order(self, stroke_first: bool) -> Result: ...
    def set_gradient(self, grad: Gradient) -> Result: ...
    def get_gradient(self) -> tuple[Result, Gradient | None]: ...

# ═══════════════════════════════════════════════════════════════════
#  Picture
# ═══════════════════════════════════════════════════════════════════

class Picture(Paint):
    def __init__(self) -> None: ...
    def load(self, path: str) -> Result: ...
    def load_raw(
        self, data_ptr: int, w: int, h: int, cs: int = 0, copy: bool = True,
    ) -> Result: ...
    def load_data(
        self, data: bytes, mimetype: str = "", rpath: str = "",
        copy: bool = True,
    ) -> Result: ...
    def set_size(self, w: float, h: float) -> Result: ...
    def get_size(self) -> tuple[Result, float, float]: ...
    def set_origin(self, x: float, y: float) -> Result: ...
    def get_origin(self) -> tuple[Result, float, float]: ...
    def get_paint(self, id: int) -> Paint | None: ...

# ═══════════════════════════════════════════════════════════════════
#  Scene
# ═══════════════════════════════════════════════════════════════════

class Scene(Paint):
    def __init__(self) -> None: ...
    def add(self, paint: Paint) -> Result: ...
    def insert(self, target: Paint, at: Paint | None = None) -> Result: ...
    def remove(self, paint: Paint | None = None) -> Result: ...
    def clear_effects(self) -> Result: ...
    def add_effect_gaussian_blur(
        self, sigma: float, direction: int = 0,
        border: int = 0, quality: int = 50,
    ) -> Result: ...
    def add_effect_drop_shadow(
        self, r: int, g: int, b: int, a: int,
        angle: float = 0, distance: float = 0,
        sigma: float = 0, quality: int = 50,
    ) -> Result: ...
    def add_effect_fill(self, r: int, g: int, b: int, a: int) -> Result: ...
    def add_effect_tint(
        self,
        black_r: int, black_g: int, black_b: int,
        white_r: int, white_g: int, white_b: int,
        intensity: float = 1.0,
    ) -> Result: ...
    def add_effect_tritone(
        self,
        sr: int, sg: int, sb: int,
        mr: int, mg: int, mb: int,
        hr: int, hg: int, hb: int,
        blend: float = 0.5,
    ) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Text
# ═══════════════════════════════════════════════════════════════════

class Text(Paint):
    def __init__(self) -> None: ...
    def set_font(self, name: str) -> Result: ...
    def set_size(self, size: float) -> Result: ...
    def set_text(self, utf8: str) -> Result: ...
    def align(self, x: float, y: float) -> Result: ...
    def layout(self, w: float, h: float) -> Result: ...
    def wrap_mode(self, mode: int) -> Result: ...
    def spacing(self, letter: float, line: float) -> Result: ...
    def set_italic(self, shear: float) -> Result: ...
    def set_outline(self, width: float, r: int, g: int, b: int) -> Result: ...
    def set_color(self, r: int, g: int, b: int) -> Result: ...
    def set_gradient(self, grad: Gradient) -> Result: ...
    def get_text_metrics(self) -> tuple[Result, TextMetrics]: ...
    @staticmethod
    def font_load(path: str) -> Result: ...
    @staticmethod
    def font_load_data(
        name: str, data: bytes, mimetype: str = "", copy: bool = True,
    ) -> Result: ...
    @staticmethod
    def font_unload(path: str) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Animation
# ═══════════════════════════════════════════════════════════════════

class Animation:
    def __init__(self) -> None: ...
    def set_frame(self, no: float) -> Result: ...
    def get_picture(self) -> Picture: ...
    def get_frame(self) -> tuple[Result, float]: ...
    def get_total_frame(self) -> tuple[Result, float]: ...
    def get_duration(self) -> tuple[Result, float]: ...
    def set_segment(self, begin: float, end: float) -> Result: ...
    def get_segment(self) -> tuple[Result, float, float]: ...
    def _del(self) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  LottieAnimation
# ═══════════════════════════════════════════════════════════════════

class LottieAnimation(Animation):
    def __init__(self) -> None: ...
    def gen_slot(self, slot: str) -> int: ...
    def apply_slot(self, id: int) -> Result: ...
    def del_slot(self, id: int) -> Result: ...
    def set_marker(self, marker: str) -> Result: ...
    def get_markers_cnt(self) -> tuple[Result, int]: ...
    def get_marker(self, idx: int) -> tuple[Result, str | None]: ...
    def tween(self, from_: float, to: float, progress: float) -> Result: ...
    def assign(self, layer: str, ix: int, var: str, val: float) -> Result: ...
    def set_quality(self, value: int) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Saver
# ═══════════════════════════════════════════════════════════════════

class Saver:
    def __init__(self) -> None: ...
    def save_paint(self, paint: Paint, path: str, quality: int = 100) -> Result: ...
    def save_animation(
        self, animation: Animation, path: str,
        quality: int = 100, fps: int = 0,
    ) -> Result: ...
    def sync(self) -> Result: ...
    def _del(self) -> Result: ...

# ═══════════════════════════════════════════════════════════════════
#  Accessor
# ═══════════════════════════════════════════════════════════════════

class Accessor:
    def __init__(self) -> None: ...
    def _del(self) -> Result: ...
    @staticmethod
    def generate_id(name: str) -> int: ...
